sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
# command to install dependencies
install:
 - pip install -r requirements.txt
script: 
 - ./run_tests.sh

